version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: java_db
      MYSQL_ROOT_PASSWORD: arti2002
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: git-manager-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/java_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: arti2002
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      REPOSITORIES_PATH: /app/.git-repositories
    ports:
      - "8080:8080"
    volumes:
      - ./.git-repositories:/app/.git-repositories
    restart: always

volumes:
  db_data: 